/*========================== begin_copyright_notice ============================

Copyright (C) 2026 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/

#include "AdaptorCommon/FreezeOutOfRangeShifts.h"
#include "Compiler/IGCPassSupport.h"
#include "common/igc_regkeys.hpp"

#include "common/LLVMWarningsPush.hpp"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/KnownBits.h"
#include "common/LLVMWarningsPop.hpp"

using namespace llvm;

namespace IGC {

// Shared implementation. Holds the logic and is used by both the legacy and the
// new-pass-manager wrappers below; it is not itself an llvm::Pass.
class FreezeOutOfRangeShifts : public InstVisitor<FreezeOutOfRangeShifts> {
public:
  FreezeOutOfRangeShifts() {}
  ~FreezeOutOfRangeShifts() {}

  static StringRef getPassName() { return "FreezeOutOfRangeShifts"; }

  bool run(Function &F);

  void visitBinaryOperator(BinaryOperator &I);
  void freezeShift(BinaryOperator &I);

private:
  bool changed = false;
  const DataLayout *DL = nullptr;
};

// Legacy Pass Manager wrapper.
class FreezeOutOfRangeShiftsLPM : public FunctionPass {
public:
  static char ID;

  FreezeOutOfRangeShiftsLPM() : FunctionPass(ID) {
    initializeFreezeOutOfRangeShiftsLPMPass(*PassRegistry::getPassRegistry());
  }

  bool runOnFunction(Function &F) override { return m_impl.run(F); }

  StringRef getPassName() const override { return FreezeOutOfRangeShifts::getPassName(); }

  void getAnalysisUsage(AnalysisUsage &AU) const override { AU.setPreservesCFG(); }

private:
  FreezeOutOfRangeShifts m_impl;
};

char FreezeOutOfRangeShiftsLPM::ID = 0;

#define PASS_FLAG "igc-freeze-out-of-range-shifts"
#define PASS_DESCRIPTION "Freeze shifts whose shift amount may be out of range"
#define PASS_CFG_ONLY false
#define PASS_ANALYSIS false
IGC_INITIALIZE_PASS_BEGIN(FreezeOutOfRangeShiftsLPM, PASS_FLAG, PASS_DESCRIPTION, PASS_CFG_ONLY, PASS_ANALYSIS)
IGC_INITIALIZE_PASS_END(FreezeOutOfRangeShiftsLPM, PASS_FLAG, PASS_DESCRIPTION, PASS_CFG_ONLY, PASS_ANALYSIS)

FunctionPass *createFreezeOutOfRangeShiftsPass() { return new FreezeOutOfRangeShiftsLPM(); }

#if LLVM_VERSION_MAJOR >= 16
PreservedAnalyses FreezeOutOfRangeShiftsNPM::run(Function &F, FunctionAnalysisManager &AM) {
  bool changed = FreezeOutOfRangeShifts().run(F);
  return changed ? PreservedAnalyses::none() : PreservedAnalyses::all();
}
#endif // LLVM_VERSION_MAJOR >= 16

bool FreezeOutOfRangeShifts::run(Function &F) {
  changed = false;
  DL = &F.getParent()->getDataLayout();
  visit(F);
  return changed;
}

void FreezeOutOfRangeShifts::freezeShift(BinaryOperator &I) {
  llvm::IRBuilder<> builder(I.getNextNode());
  Value *FI = builder.CreateFreeze(&I, "freeze");
  I.replaceAllUsesWith(FI);
  cast<Instruction>(FI)->setOperand(0, &I);
}

void FreezeOutOfRangeShifts::visitBinaryOperator(BinaryOperator &I) {
  switch (I.getOpcode()) {
  case Instruction::Shl:
  case Instruction::LShr:
  case Instruction::AShr:
    // Stop propagation of poison values generated by LLVM when the shift amount is greater than or equal to the bit
    // width of the shifted type.
    {
      Type *ScalarTy = I.getType()->getScalarType();
      if (!ScalarTy->isIntegerTy())
        break;

      // While a freeze on a never-poison value should resolve to a no-op, LLVM passes are sloppy about looking through
      // it and can skip valuable optimizations. So skip the shifts that provably cannot produce poison: constant
      // amounts, amounts that are already masked, amounts extended from a narrower type.
      KnownBits Known = computeKnownBits(I.getOperand(1), *DL);
      if (Known.getMaxValue().ult(ScalarTy->getIntegerBitWidth()))
        break;

      freezeShift(I);
      changed = true;
      break;
    }
  default:
    break;
  }
}

} // namespace IGC
