/*========================== begin_copyright_notice ============================

Copyright (C) 2019-2023 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/


// This file is autogenerated.  It is not currently part of the build process as
// we don't expect to update that often.

static Type* _struct_RTStackFormat__RTStack(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::RTStack";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__HWRayData(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__HWRayData(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::HWRayData";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__MemHit(M),
      _struct_RTStackFormat__MemHit(M),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__MemRay(M);
        return ArrayType::get(EltTy, 2);
      }(),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__MemTravStack(M);
        return ArrayType::get(EltTy, 2);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__MemHit(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::MemHit";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_RTStackFormat__MemHit__RT(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_RTStackFormat__MemHit__RT(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.RTStackFormat::MemHit::RT";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__MemHit__RT__Xe(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__MemHit__RT__Xe(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::MemHit::RT::Xe";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      Type::getFloatTy(M.getContext()),
      Type::getFloatTy(M.getContext()),
      Type::getFloatTy(M.getContext()),
      _union_anon(M),
      _union_anon_0(M),
      _union_anon_2(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_0(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.0";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_2(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.2";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__MemRay(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::MemRay";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      Type::getFloatTy(M.getContext()),
      Type::getFloatTy(M.getContext()),
      _union_RTStackFormat__MemRay__RT(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_RTStackFormat__MemRay__RT(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.RTStackFormat::MemRay::RT";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__MemRay__RT__Xe(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__MemRay__RT__Xe(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::MemRay::RT::Xe";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_anon_4(M),
      _union_anon_6(M),
      _union_anon_8(M),
      _union_anon_10(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_4(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.4";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_6(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.6";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_8(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.8";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_10(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.10";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__MemTravStack(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::MemTravStack";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_anon_12(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_12(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.12";
    Type* Tys[] = {
      _struct_anon_14(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_anon_14(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.anon.14";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 32);
        return ArrayType::get(EltTy, 4);
      }(),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__NodeInfo(M);
        return ArrayType::get(EltTy, 4);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__NodeInfo(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::NodeInfo";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 8),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__RayQueryObject(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::RayQueryObject";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__RTStack(M),
      _struct_RTStackFormat__RayQueryStateInfo(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__RayQueryStateInfo(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::RayQueryStateInfo";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 8),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__SMStack(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::SMStack";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__SMRayData(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__SMRayData(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::SMRayData";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__MemHit(M),
      _struct_RTStackFormat__MemHit(M),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__MemRay(M);
        return ArrayType::get(EltTy, 2);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__SWHotZone_v1(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::SWHotZone_v1";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__StackPtrDRIEncoding(M),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 8);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__StackPtrDRIEncoding(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::StackPtrDRIEncoding";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__StackPtrAndBudges(M),
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__StackPtrAndBudges(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::StackPtrAndBudges";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 16),
      _union_anon_15(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_15(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.15";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 16),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__SWHotZone_v2(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::SWHotZone_v2";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 32);
        return ArrayType::get(EltTy, 3);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_IGC__RayDispatchGlobalData(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.IGC::RayDispatchGlobalData";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      _union_anon_17(M),
      _union_anon_19(M),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 32);
        return ArrayType::get(EltTy, 3);
      }(),
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_17(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.17";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_19(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.19";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_IGC__TypeHoleGlobalRootSig(Module &M, Type* TypeHoleGlobalRootSig)
{
  return
  [&] {
    (void)M;
    IGC_ASSERT_MESSAGE(checkAlign(M, cast<StructType>(TypeHoleGlobalRootSig), 8), "type not aligned!");
    return TypeHoleGlobalRootSig;
  }();
}
static Type* _struct_RTStackFormat__InstanceLeaf(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InstanceLeaf";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__InstanceLeaf__Part0(M),
      _struct_RTStackFormat__InstanceLeaf__Part1(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__InstanceLeaf__Part0(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InstanceLeaf::Part0";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_RTStackFormat__InstanceLeaf__Part0__RT(M),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_RTStackFormat__InstanceLeaf__Part0__RT(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.RTStackFormat::InstanceLeaf::Part0::RT";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__InstanceLeaf__Part0__RT__Xe(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__InstanceLeaf__Part0__RT__Xe(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InstanceLeaf::Part0::RT::Xe";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
      _union_anon_21(M),
      IntegerType::get(M.getContext(), 64),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_21(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.21";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__InstanceLeaf__Part1(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InstanceLeaf::Part1";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__QuadLeaf(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::QuadLeaf";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__PrimLeafDesc(M),
      IntegerType::get(M.getContext(), 32),
      _union_RTStackFormat__QuadLeaf__RT(M),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__PrimLeafDesc(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::PrimLeafDesc";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
      _union_RTStackFormat__PrimLeafDesc__RT(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_RTStackFormat__PrimLeafDesc__RT(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.RTStackFormat::PrimLeafDesc::RT";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__PrimLeafDesc__RT__Xe(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__PrimLeafDesc__RT__Xe(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::PrimLeafDesc::RT::Xe";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_anon_23(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_23(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.23";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_RTStackFormat__QuadLeaf__RT(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.RTStackFormat::QuadLeaf::RT";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__QuadLeaf__RT__Xe(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__QuadLeaf__RT__Xe(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::QuadLeaf::RT::Xe";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _union_anon_25(M),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _union_anon_25(Module &M)
{
  return
  [&] {
    StringRef StructName = "union.anon.25";
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 32),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__ProceduralLeaf(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::ProceduralLeaf";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_RTStackFormat__PrimLeafDesc(M),
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 32);
        return ArrayType::get(EltTy, 13);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_IGC__RTGlobalsAndRootSig(Module &M, Type* TypeHoleGlobalRootSig)
{
  return
  [&] {
    StringRef StructName = "struct.IGC::RTGlobalsAndRootSig";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      _struct_IGC__RayDispatchGlobalData(M),
      _struct_IGC__TypeHoleGlobalRootSig(M, TypeHoleGlobalRootSig),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__BVH(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::BVH";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 64),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 32),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__InternalNode(M);
        return ArrayType::get(EltTy, 1);
      }(),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__QuadLeaf(M);
        return ArrayType::get(EltTy, 1);
      }(),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__ProceduralLeaf(M);
        return ArrayType::get(EltTy, 1);
      }(),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__InstanceLeaf(M);
        return ArrayType::get(EltTy, 1);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 32);
        return ArrayType::get(EltTy, 1);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 124);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__InternalNode(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InternalNode";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      [&] {
        auto *EltTy =
          Type::getFloatTy(M.getContext());
        return ArrayType::get(EltTy, 3);
      }(),
      IntegerType::get(M.getContext(), 32),
      IntegerType::get(M.getContext(), 8),
      IntegerType::get(M.getContext(), 8),
      IntegerType::get(M.getContext(), 8),
      IntegerType::get(M.getContext(), 8),
      IntegerType::get(M.getContext(), 8),
      IntegerType::get(M.getContext(), 8),
      [&] {
        auto *EltTy =
          _struct_RTStackFormat__InternalNode__ChildData(M);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
      [&] {
        auto *EltTy =
          IntegerType::get(M.getContext(), 8);
        return ArrayType::get(EltTy, 6);
      }(),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _struct_RTStackFormat__InternalNode__ChildData(Module &M)
{
  return
  [&] {
    StringRef StructName = "struct.RTStackFormat::InternalNode::ChildData";
    if (auto *Ty = IGCLLVM::getTypeByName(M, StructName))
      return Ty;
    Type* Tys[] = {
      IntegerType::get(M.getContext(), 8),
    };
    return StructType::create(M.getContext(), Tys, StructName, false);
  }();
}
static Type* _gettype_RTStack2(Module &M)
{
  return
  _struct_RTStackFormat__RTStack(M);
}

static Type* _gettype_HWRayData2(Module &M)
{
  return
  _struct_RTStackFormat__HWRayData(M);
}

static Type* _gettype_RayQueryObject2(Module &M)
{
  return
  _struct_RTStackFormat__RayQueryObject(M);
}

static Type* _gettype_SMStack2(Module &M)
{
  return
  _struct_RTStackFormat__SMStack(M);
}

static Type* _gettype_SMRayData2(Module &M)
{
  return
  _struct_RTStackFormat__SMRayData(M);
}

static Type* _gettype_SWHotZone_v1(Module &M)
{
  return
  _struct_RTStackFormat__SWHotZone_v1(M);
}

static Type* _gettype_SWHotZone_v2(Module &M)
{
  return
  _struct_RTStackFormat__SWHotZone_v2(M);
}

static Type* _gettype_RayDispatchGlobalData(Module &M)
{
  return
  _struct_IGC__RayDispatchGlobalData(M);
}

static Type* _gettype_InstanceLeaf(Module &M)
{
  return
  _struct_RTStackFormat__InstanceLeaf(M);
}

static Type* _gettype_QuadLeaf(Module &M)
{
  return
  _struct_RTStackFormat__QuadLeaf(M);
}

static Type* _gettype_ProceduralLeaf(Module &M)
{
  return
  _struct_RTStackFormat__ProceduralLeaf(M);
}

static Type* _gettype_RTGlobalsAndRootSig(Module &M, Type* TypeHoleGlobalRootSig)
{
  return
  _struct_IGC__RTGlobalsAndRootSig(M, TypeHoleGlobalRootSig);
}

static Type* _gettype_BVH(Module &M)
{
  return
  _struct_RTStackFormat__BVH(M);
}

auto* _get_rtMemBasePtr_Xe()
{
  auto* V_0 = getGlobalBufferPtr();
  auto* V_1 = CreateInBoundsGEP(V_0, { getInt64(0), getInt32(0) });
  auto* V_2 = CreateLoad(V_1);
  setInvariantLoad(V_2);
  return V_2;
}

auto* _get_maxBVHLevels_Xe()
{
  auto* V_0 = getGlobalBufferPtr();
  auto* V_1 = CreateInBoundsGEP(V_0, { getInt64(0), getInt32(4) });
  auto* V_2 = CreateLoad(V_1);
  setInvariantLoad(V_2);
  return V_2;
}

auto* _get_statelessScratchPtr_Xe()
{
  auto* V_0 = getGlobalBufferPtr();
  auto* V_1 = CreateInBoundsGEP(V_0, { getInt64(0), getInt32(15) });
  auto* V_2 = CreateLoad(V_1);
  setInvariantLoad(V_2);
  return V_2;
}

Value* _gepof_BVH_rootNodeOffset(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_dispRaysIndex_v2(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_StackOffset_v2(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CompressedDispatchRayIndices_v1(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_StackOffset_v1(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_BudgeBits_v1(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitT(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitT2(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitT(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitU(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitU(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitTopOfInstLeafPtr(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(5),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitTopOfInstLeafPtr(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(5),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitTopOfPrimLeafPtr(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(4),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitTopOfPrimLeafPtr(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(4),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitTopOfPrimIndexDelta(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(3),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitTopOfPrimIndexDelta(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(3),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_CommittedHitFrontFaceDword(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(3),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_PotentialHitFrontFaceDword(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(3),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_topOfNodePtrAndFlags(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(4),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_hitGroupShaderRecordInfo(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(4),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_missShaderRecordInfo(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(4),
    this->getInt32(0),
    this->getInt32(2),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_topOfInstanceLeafPtr(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(4),
    this->getInt32(0),
    this->getInt32(3),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_MemRay_org(Value* p, Value* idx1, Value* idx2, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(0),
    idx2,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_MemRay_dir(Value* p, Value* idx1, Value* idx2, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(1),
    idx2,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_MemRay_tnear(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(2),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_MemRay_tfar(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
    this->getInt32(3),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_RQO_rtStack(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_RQO_TRCtrl(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_instanceID(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(1),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_instanceIndex(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(2),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_world2obj_vx(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_world2obj_vy(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(2),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_world2obj_vz(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(3),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_obj2world_p(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(4),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_obj2world_vx(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(3),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_obj2world_vy(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(4),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_obj2world_vz(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(5),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_world2obj_p(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(6),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_InstanceLeaf_instContToHitGroupIndex(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_QuadLeaf_primIndex0(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(1),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_QuadLeaf_topOfGeomIndex(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_ProceduralLeaf__primIndex(Value* p, Value* idx1, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(2),
    idx1,
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

Value* _gepof_ProceduralLeaf_topOfGeomIndex(Value* p, const Twine &Name = "")
{
  Value* Indices[] = {
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(1),
    this->getInt32(0),
    this->getInt32(0),
    this->getInt32(0),
  };
  return this->CreateInBoundsGEP(p, Indices, Name);
}

void _createPotentialHit2CommittedHit_Xe(Value* arg_0)
{
  auto* V_1 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0) });
  auto* V_2 = CreateBitCast(V_1, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  auto* V_3 = CreateLoad(V_2);
  auto* V_4 = CreateBitCast(arg_0, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  CreateStore(V_3, V_4);
  auto* V_5 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(1) });
  auto* V_6 = CreateBitCast(V_5, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  auto* V_7 = CreateLoad(V_6);
  auto* V_8 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(1) });
  auto* V_9 = CreateBitCast(V_8, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  CreateStore(V_7, V_9);
  auto* V_10 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(2) });
  auto* V_11 = CreateBitCast(V_10, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  auto* V_12 = CreateLoad(V_11);
  auto* V_13 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(2) });
  auto* V_14 = CreateBitCast(V_13, PointerType::get(getInt32Ty(), arg_0->getType()->getPointerAddressSpace()));
  CreateStore(V_12, V_14);
  auto* V_15 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(3), getInt32(0) });
  auto* V_16 = CreateLoad(V_15);
  auto* V_17 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(3), getInt32(0) });
  CreateStore(V_16, V_17);
  auto* V_18 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(4), getInt32(0) });
  auto* V_19 = CreateLoad(V_18);
  auto* V_20 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(4), getInt32(0) });
  CreateStore(V_19, V_20);
  auto* V_21 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(5), getInt32(0) });
  auto* V_22 = CreateLoad(V_21);
  auto* V_23 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(5), getInt32(0) });
  CreateStore(V_22, V_23);
  return;
}

void _createTraceRayInlinePrologue_Xe(Value* arg_0, Value* arg_1, Value* arg_2, Value* arg_3, Value* arg_4, Value* arg_5)
{
  auto* V_6 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(2), getInt64(0) });
  auto* V_7 = CreateBitCast(V_6, PointerType::get(IGCLLVM::FixedVectorType::get(getFloatTy(), 8), arg_0->getType()->getPointerAddressSpace()));
  CreateStore(arg_1, V_7);
  auto* V_8 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(2), getInt64(0), getInt32(4), getInt32(0) });
  auto* V_9 = CreateInBoundsGEP(V_8, { getInt64(0), getInt32(0), getInt32(0) });
  auto* V_10 = CreateBitCast(V_8, PointerType::get(getInt16Ty(), arg_0->getType()->getPointerAddressSpace()));
  auto* V_11 = CreateInBoundsGEP(V_10, { getInt64(3) });
  auto* V_12 = CreateLoad(V_11);
  auto* V_13 = CreateZExt(V_12, getInt32Ty());
  auto* V_14 = CreateOr(V_13, arg_3);
  auto* V_15 = CreateAnd(V_14, getInt32(1023));
  auto* V_16 = CreateZExt(V_15, getInt64Ty());
  auto* V_17 = CreateShl(V_16, getInt64(48));
  auto* V_18 = CreateOr(V_17, arg_2);
  CreateStore(V_18, V_9);
  auto* V_19 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(2), getInt64(0), getInt32(4), getInt32(0), getInt32(3), getInt32(0) });
  auto* V_20 = CreateAnd(arg_4, getInt32(255));
  auto* V_21 = CreateZExt(V_20, getInt64Ty());
  auto* V_22 = CreateShl(V_21, getInt64(48));
  CreateStore(V_22, V_19);
  auto* V_23 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0) });
  CreateStore(arg_5, V_23);
  auto* V_24 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(0), getInt32(0), getInt32(0), getInt32(3), getInt32(0) });
  CreateStore(getInt32(0), V_24);
  auto* V_25 = CreateInBoundsGEP(arg_0, { getInt64(0), getInt32(0), getInt32(1), getInt32(0), getInt32(0), getInt32(3), getInt32(0) });
  CreateStore(getInt32(0), V_25);
  return;
}

