; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;=========================== begin_copyright_notice ============================
;
; Copyright (C) 2022-2024 Intel Corporation
;
; SPDX-License-Identifier: MIT
;
;============================ end_copyright_notice =============================

; REQUIRES: regkeys
; UNSUPPORTED: llvm-17-plus
; RUN: igc_opt --typed-pointers -igc-InsertBranchOpt -regkey EnableAtomicBranch=768 -S %s | FileCheck %s

; EnableAtomicBranch=768 enables CheckOr (0x100) and CheckAnd (0x200) modes.
; These read the current memory value first and only perform the atomic when it
; would actually change memory:
; CheckOr:  skip the atomic OR  when (mem | src) == mem (no new bits set).
; CheckAnd: skip the atomic AND when (mem & src) == mem (no bits cleared).

define i32 @atomicCheckOr(i32 %mem, i32 %val) {
; CHECK-LABEL: @atomicCheckOr(
; CHECK-NEXT:    [[ADDBEFORE:%.*]] = add i32 [[MEM:%.*]], 10
; CHECK-NEXT:    [[SOMEUNKNOWN:%.*]] = add i32 [[VAL:%.*]], 10
; CHECK-NEXT:    [[TMP1:%.*]] = call <4 x float> @llvm.genx.GenISA.ldrawvector.indexed.v4f32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 [[MEM]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[TMP1]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast float [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = or i32 [[TMP3]], [[SOMEUNKNOWN]]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ne i32 [[TMP4]], [[TMP3]]
; CHECK-NEXT:    br i1 [[TMP5]], label [[ATOMIC_IF_TRUE:%.*]], label [[ATOMIC_IF_END:%.*]]
; CHECK:       atomic.if.true:
; CHECK-NEXT:    [[ATOMIC:%.*]] = call i32 @llvm.genx.GenISA.intatomicraw.i32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 [[MEM]], i32 [[SOMEUNKNOWN]], i32 9)
; CHECK-NEXT:    br label [[ATOMIC_IF_END]]
; CHECK:       atomic.if.end:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i32 [ [[ATOMIC]], [[ATOMIC_IF_TRUE]] ], [ [[TMP3]], [[TMP0:%.*]] ]
; CHECK-NEXT:    [[ADDAFTER:%.*]] = add i32 [[TMP6]], 15
; CHECK-NEXT:    ret i32 [[ADDAFTER]]
;
  %addBefore = add i32 %mem, 10
  %someUnknown = add i32 %val, 10
  %atomic = call i32 @llvm.genx.GenISA.intatomicraw.i32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 %mem, i32 %someUnknown, i32 9)
  %addAfter = add i32 %atomic, 15
  ret i32 %addAfter
}

define i32 @atomicCheckAnd(i32 %mem, i32 %val) {
; CHECK-LABEL: @atomicCheckAnd(
; CHECK-NEXT:    [[ADDBEFORE:%.*]] = add i32 [[MEM:%.*]], 10
; CHECK-NEXT:    [[SOMEUNKNOWN:%.*]] = add i32 [[VAL:%.*]], 10
; CHECK-NEXT:    [[TMP1:%.*]] = call <4 x float> @llvm.genx.GenISA.ldrawvector.indexed.v4f32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 [[MEM]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[TMP1]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast float [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[TMP3]], [[SOMEUNKNOWN]]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ne i32 [[TMP4]], [[TMP3]]
; CHECK-NEXT:    br i1 [[TMP5]], label [[ATOMIC_IF_TRUE:%.*]], label [[ATOMIC_IF_END:%.*]]
; CHECK:       atomic.if.true:
; CHECK-NEXT:    [[ATOMIC:%.*]] = call i32 @llvm.genx.GenISA.intatomicraw.i32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 [[MEM]], i32 [[SOMEUNKNOWN]], i32 8)
; CHECK-NEXT:    br label [[ATOMIC_IF_END]]
; CHECK:       atomic.if.end:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i32 [ [[ATOMIC]], [[ATOMIC_IF_TRUE]] ], [ [[TMP3]], [[TMP0:%.*]] ]
; CHECK-NEXT:    [[ADDAFTER:%.*]] = add i32 [[TMP6]], 15
; CHECK-NEXT:    ret i32 [[ADDAFTER]]
;
  %addBefore = add i32 %mem, 10
  %someUnknown = add i32 %val, 10
  %atomic = call i32 @llvm.genx.GenISA.intatomicraw.i32.p131073v4f32(<4 x float> addrspace(131073)* null, i32 %mem, i32 %someUnknown, i32 8)
  %addAfter = add i32 %atomic, 15
  ret i32 %addAfter
}

; Function Desc:
; Output:
; Arg 0: Dst Buffer
; Arg 1: dst address
; Arg 2: src0
; Arg 3: Instruction type (add, or, xor etc)
; Function Attrs: argmemonly nounwind
declare i32 @llvm.genx.GenISA.intatomicraw.i32.p131073v4f32(<4 x float> addrspace(131073)*, i32, i32, i32) #0

attributes #0 = { argmemonly nounwind }
