/*========================== begin_copyright_notice ============================

Copyright (C) 2017-2021 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/

#pragma once

#include "Compiler/MetaDataUtilsWrapper.h"
#include "Compiler/CodeGenContextWrapper.hpp"

#include "common/LLVMWarningsPush.hpp"
#include <llvm/Pass.h>
#include <llvm/IR/PassManager.h>
#include "common/LLVMWarningsPop.hpp"

#include "AdaptorOCL/CLElfLib/ElfReader.h"

#include <vector>
#include <set>
#include <queue>

namespace IGC {
/// This pass imports built-in functions from source module to destination module.
/// Shared implementation. Holds the logic and is used by both the legacy and the new-pass-manager
/// wrappers below; it is not itself an llvm::Pass. The CodeGenContext and MetaDataUtils are injected
/// by the caller (run).
class BIImport {
public:
  BIImport() {}

  /// @brief Main entry point.
  ///        Find all builtins to import, and import them along with callees and globals.
  /// @param M The destination module.
  bool run(llvm::Module &M, CodeGenContext *Ctx, IGC::IGCMD::MetaDataUtils *MdUtils);

  static void supportOldManglingSchemes(llvm::Module &M);
  static std::unique_ptr<llvm::Module> Construct(llvm::Module &M, CLElfLib::CElfReader *pElfReader, bool hasSizet);

protected:
  // Type used to hold a vector of Functions and augment it during traversal.
  typedef std::vector<llvm::Function *> TFunctionsVec;
  /// @brief Get all the functions called by given function.
  /// @param [IN] pFunc The given function.
  /// @param [OUT] calledFuncs The list of all functions called by pFunc.
  static void GetCalledFunctions(const llvm::Function *pFunc, TFunctionsVec &calledFuncs);

  /// @brief  Remove function bitcasts that sometimes may appear due to the changed in the way
  ///         the BiFs are linked. We can remove this code once llvm implements typeless pointers.
  void removeFunctionBitcasts(llvm::Module &M);

  /// @brief  Initialize values for global flags needed for the built-ins (FlushDenormal).
  ///         Only initializes flags that the built-ins need.
  void InitializeBIFlags(llvm::Module &M);

  /// @brief  Search through all builtin modules for the specified function.
  /// @param  funcName - name of func to search for.
  static llvm::Function *GetBuiltinFunction(llvm::StringRef funcName, llvm::Module *GenericModule);
  /// @brief  Read elf Header file that is constructed by Build Packager and write to a DenseMap.
  static void WriteElfHeaderToMap(llvm::DenseMap<llvm::StringRef, int> &Map, char *pData, size_t dataSize);

  /// @brief Fix SPIR builtins return type
  void fixSPIRFunctionsReturnType(llvm::Module &M);

  /// @brief Fix invalid bitcasts generated by older Clang
  void fixInvalidBitcasts(llvm::Module &M);

  /// @brief Adds definitions for functions such as __builtin_IB_cast_object_to_generic_ptr which can be only defined in
  /// LLVM IR due to Clang not supporting bitcasts between TargetExtTy and other types.
  void addOCLObjectCastFunctionDefinitions(llvm::Module &M);
};

// Legacy Pass Manager wrapper.
class BIImportLPM : public llvm::ModulePass {
public:
  static char ID;

  BIImportLPM();

  void getAnalysisUsage(llvm::AnalysisUsage &AU) const override {
    AU.addRequired<MetaDataUtilsWrapper>();
    AU.addRequired<CodeGenContextWrapper>();
  }

  llvm::StringRef getPassName() const override { return "BIImport"; }

  bool runOnModule(llvm::Module &M) override {
    return m_impl.run(M, getAnalysis<CodeGenContextWrapper>().getCodeGenContext(),
                      getAnalysis<MetaDataUtilsWrapper>().getMetaDataUtils());
  }

private:
  BIImport m_impl;
};

#if LLVM_VERSION_MAJOR >= 16
// New Pass Manager wrapper. name() returns the legacy pass argument so that
// PrintBefore/PrintAfter=<pass argument> matches under the new pass manager.
class BIImportNPM : public llvm::PassInfoMixin<BIImportNPM> {
public:
  llvm::PreservedAnalyses run(llvm::Module &M, llvm::ModuleAnalysisManager &AM);
  static llvm::StringRef name() { return "igc-builtin-import"; }
  static llvm::StringRef getPassName() { return "BIImport"; }
  static bool isRequired() { return true; }
};
#endif // LLVM_VERSION_MAJOR >= 16

} // namespace IGC

extern "C" llvm::ModulePass *createBuiltInImportPass();

namespace IGC {
// Shared implementation. Holds the logic and is used by both the legacy and the
// new-pass-manager wrappers below; it is not itself an llvm::Pass.
class PreBIImportAnalysis {
public:
  PreBIImportAnalysis() {}
  ~PreBIImportAnalysis() {}

  static llvm::StringRef getPassName() { return "PreBIImportAnalysis"; }

  /// @brief  Main entry point.
  /// @param  M The destination module.
  bool run(llvm::Module &M, IGCMD::MetaDataUtils *pMdUtils, ModuleMetaData *pModMD, CodeGenContext *pCtx);

  static const llvm::StringRef OCL_GET_GLOBAL_OFFSET;
  static const llvm::StringRef OCL_GET_LOCAL_ID;
  static const llvm::StringRef OCL_GET_GROUP_ID;
  static const llvm::StringRef OCL_GET_SUBGROUP_ID_IGC_SPVIR;
  static const llvm::StringRef OCL_GET_SUBGROUP_ID_KHR_SPVIR;
  static const llvm::StringRef OCL_GET_SUBGROUP_ID;
  static const llvm::StringRef OCL_SUBGROUP_BLOCK_PREFIX;
  static const llvm::StringRef OCL_SUBGROUP_IMAGE_BLOCK_PREFIX;
  static const llvm::StringRef OCL_S_MUL_HI_PREFIX;
  static const llvm::StringRef OCL_U_MUL_HI_PREFIX;
  static const llvm::StringRef OCL_S_MAD_SAT_PREFIX;
  static const llvm::StringRef OCL_U_MAD_SAT_PREFIX;
  static const llvm::StringRef OCL_S_MAD_HI_PREFIX;
  static const llvm::StringRef OCL_U_MAD_HI_PREFIX;
  static const llvm::StringRef OCL_SPIRV_PREFIX;
  static const llvm::StringRef OCL_I64_SUFFIX;
  static const llvm::StringRef OCL_V2I64_SUFFIX;
  static const llvm::StringRef OCL_V3I64_SUFFIX;
  static const llvm::StringRef OCL_V4I64_SUFFIX;
  static const llvm::StringRef OCL_V8I64_SUFFIX;
  static const llvm::StringRef OCL_V16I64_SUFFIX;
};

// Legacy Pass Manager wrapper.
class PreBIImportAnalysisLPM : public llvm::ModulePass {
public:
  // Pass identification, replacement for typeid
  static char ID;

  PreBIImportAnalysisLPM();
  ~PreBIImportAnalysisLPM() {}

  virtual llvm::StringRef getPassName() const override { return PreBIImportAnalysis::getPassName(); }

  void getAnalysisUsage(llvm::AnalysisUsage &AU) const override {
    AU.addRequired<MetaDataUtilsWrapper>();
    AU.addRequired<CodeGenContextWrapper>();
  }

  virtual bool runOnModule(llvm::Module &M) override {
    return m_impl.run(M, getAnalysis<MetaDataUtilsWrapper>().getMetaDataUtils(),
                      getAnalysis<MetaDataUtilsWrapper>().getModuleMetaData(),
                      getAnalysis<CodeGenContextWrapper>().getCodeGenContext());
  }

private:
  PreBIImportAnalysis m_impl;
};

#if LLVM_VERSION_MAJOR >= 16
// New Pass Manager wrapper. name() returns the legacy pass argument so that
// PrintBefore/PrintAfter=<pass argument> matches under the new pass manager.
class PreBIImportAnalysisNPM : public llvm::PassInfoMixin<PreBIImportAnalysisNPM> {
public:
  llvm::PreservedAnalyses run(llvm::Module &M, llvm::ModuleAnalysisManager &AM);
  static llvm::StringRef name() { return "igc-Pre-BIImport-Analysis"; }
  static bool isRequired() { return true; }

private:
  PreBIImportAnalysis m_impl;
};
#endif // LLVM_VERSION_MAJOR >= 16

} // namespace IGC
