#
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

FROM ubuntu:20.04
LABEL maintainer="marcin.naczk@intel.com"
ENV DEBIAN_FRONTEND="noninteractive"

ARG BUILD_OS
ARG LLVM_VERSION
ARG COMPILER

RUN echo "[Build Status Dockerfile] Dockerfile start working"
RUN echo "[Build Status Dockerfile] BUILD_OS = ${BUILD_OS}"
RUN echo "[Build Status Dockerfile] LLVM_VERSION = ${LLVM_VERSION}"
RUN echo "[Build Status Dockerfile] COMPILER = ${COMPILER}"

COPY . /home
RUN /bin/bash -c "BUILD_OS=${BUILD_OS} LLVM_VERSION=${LLVM_VERSION} COMPILER=${COMPILER} sh /home/buildIGC.sh"