; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
;=========================== begin_copyright_notice ============================
;
; Copyright (C) 2026 Intel Corporation
;
; SPDX-License-Identifier: MIT
;
;============================ end_copyright_notice =============================
;
; Test: a same-condition candidate must be rejected if an arm block switches to
; a different predicate before the merged path completes.
;
; Pattern:
;   entry:  br i1 %cmp -> true1 / false1
;   merge1: br i1 %cmp -> true2 / false2
;   true2:  br i1 %other -> sink.t / sink.f
;
; The second branch still matches the same %cmp, but the true arm itself carries
; a different predicate.  Merging that chain would inline a block that branches on
; %other and would require a poison repair path.
;
; REQUIRES: llvm-22-plus, !llvm-23-plus
; RUN: igc_opt --opaque-pointers %s -S -o - -diamond-chain-merge | FileCheck %s

define spir_kernel void @mixed_condition_in_source_skip(i32 %a, i32 %b,
                                                      ptr addrspace(1) align 4 %out) #0 {
; CHECK-LABEL: define spir_kernel void @mixed_condition_in_source_skip(
; CHECK-NOT: .dcm
; CHECK: entry:
; CHECK:   [[CMP:%.*]] = icmp eq i32 %a, 0
; CHECK:   br i1 [[CMP]], label %true1, label %false1
; CHECK: merge1:
; CHECK:   br i1 [[CMP]], label %true2, label %false2
; CHECK: true2:
; CHECK:   [[OTHER:%.*]] = icmp eq i32 %b, 0
; CHECK:   br i1 [[OTHER]], label %sink.t, label %sink.f

entry:
  %cmp = icmp eq i32 %a, 0
  br i1 %cmp, label %true1, label %false1

true1:
  %v1 = add i32 %a, 1
  store i32 %v1, ptr addrspace(1) %out, align 4
  br label %merge1

false1:
  %v2 = sub i32 %a, 1
  store i32 %v2, ptr addrspace(1) %out, align 4
  br label %merge1

merge1:
  br i1 %cmp, label %true2, label %false2

true2:
  %other = icmp eq i32 %b, 0
  br i1 %other, label %sink.t, label %sink.f

false2:
  %v3 = add i32 %a, 2
  store i32 %v3, ptr addrspace(1) %out, align 4
  br label %exit

sink.t:
  %tval = add i32 %a, 10
  store i32 %tval, ptr addrspace(1) %out, align 4
  br label %exit

sink.f:
  %fval = sub i32 %a, 10
  store i32 %fval, ptr addrspace(1) %out, align 4
  br label %exit

exit:
  ret void
}

attributes #0 = { nounwind }
