; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
;=========================== begin_copyright_notice ============================
;
; Copyright (C) 2026 Intel Corporation
;
; SPDX-License-Identifier: MIT
;
;============================ end_copyright_notice =============================
;
;
; REQUIRES: llvm-22-plus, !llvm-23-plus
; RUN: igc_opt --opaque-pointers %s -S -o - -diamond-chain-merge | FileCheck %s

define spir_kernel void @entry(float %a, ptr addrspace(1) align 4 captures(none) %b) #0 {
; CHECK-LABEL: define spir_kernel void @entry(
; CHECK-SAME: float [[A:%.*]], ptr addrspace(1) align 4 captures(none) [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[A]], 0.000000e+00
; CHECK-NEXT:    br i1 [[CMP]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[A]], [[A]]
; CHECK-NEXT:    store float [[MUL]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = fmul float [[A]], [[A]]
; CHECK-NEXT:    [[TMP1:%.*]] = fmul float [[TMP0]], [[MUL]]
; CHECK-NEXT:    store float [[TMP1]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul float [[A]], [[A]]
; CHECK-NEXT:    [[TMP3:%.*]] = fmul float [[TMP2]], [[TMP1]]
; CHECK-NEXT:    store float [[TMP3]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    br label %[[END:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    store float [[A]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = fmul float [[A]], [[A]]
; CHECK-NEXT:    store float [[TMP4]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = fmul float [[A]], [[TMP4]]
; CHECK-NEXT:    store float [[TMP5]], ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    br label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    ret void
;
entry:
  %cmp = fcmp oeq float %a, 0.000000e+00
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  %mul = fmul float %a, %a
  br label %cond.false

cond.false:                                       ; preds = %entry, %cond.true
  %data = phi float [ %a, %entry ], [ %mul, %cond.true ]
  store float %data, ptr addrspace(1) %b, align 4
  br i1 %cmp, label %cond.true.1, label %cond.false.1

  cond.true.1:                                      ; preds = %cond.false
  %mul2 = fmul float %a, %a
  br label %cond.false.1

cond.false.1:                                     ; preds = %cond.false.1, %cond.true.1
  %data2_1 = phi float [ %a, %cond.false ], [ %mul2, %cond.true.1 ]
  %data2 = fmul float %data2_1, %data
  store float %data2, ptr addrspace(1) %b, align 4
  br i1 %cmp, label %cond.true.2, label %cond.false.2

cond.true.2:                                      ; preds = %cond.false.1
  %mul3 = fmul float %a, %a
  br label %cond.false.2

cond.false.2:                                     ; preds = %cond.false.2, %cond.true.2
  %data3_1 = phi float [ %a, %cond.false.1 ], [ %mul3, %cond.true.2 ]
  %data3 = fmul float %data3_1, %data2
  store float %data3, ptr addrspace(1) %b, align 4
  br label %end

end:
  ret void
}
