;=========================== begin_copyright_notice ============================
;
; Copyright (C) 2026 Intel Corporation
;
; SPDX-License-Identifier: MIT
;
;============================ end_copyright_notice =============================

; REQUIRES: regkeys
; UNSUPPORTED: llvm-17-plus
;
; Test that a heterogeneous struct alloca is SoA-promoted even when individual
; fields are accessed via constant-offset i8 GEPs (a pattern generated by
; LLVM's memcpy lowering for ShaderData-like struct sub-field copies).
;
; The pattern:
;   %ep  = getelementptr inbounds [64 x %S], ...%arr, i64 0, i64 %idx  ; element %S*
;   %ep8 = bitcast %S* %ep to i8*                                      ; byte pointer
;   %fp8 = getelementptr inbounds i8, i8* %ep8, i64 8                  ; i8 GEP at offset 8
;   %ip  = bitcast i8* %fp8 to i32*                                    ; typed pointer
;   store i32 42, i32* %ip                                             ; field store
;
; RUN: igc_opt --typed-pointers --ocl --platformPtl --igc-private-mem-resolution \
; RUN:         --regkey EnablePrivMemNewSOATranspose=1,EnableAggressiveSOAPromotion=1 -S %s | FileCheck %s
;

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32"
target triple = "spir64-unknown-unknown"

; Heterogeneous struct: { float x, float y, i32 id, [4 x i8] pad }
; sizeof(%S) = 16 bytes.  All leaf scalars are 4-byte aligned and the
; [4 x i8] padding has a total size of 4 bytes (= 1 × SOAPartitionBytes),
; so checkStruct accepts it and SOAPartitionBytes = 4.
%S = type { float, float, i32, [4 x i8] }

; CHECK-LABEL: @test
;;
;; Prolog: SoA lane offset must use SOAPartitionBytes=4, NOT struct stride 16.
;;
; CHECK:       [[laneId16:%.*]] = call i16 @llvm.genx.GenISA.simdLaneId()
; CHECK:       [[laneId:%.*]]   = zext i16 [[laneId16]] to i32
; CHECK:       [[simdSize:%.*]] = call i32 @llvm.genx.GenISA.simdSize()
; CHECK:       mul i32 [[laneId]], 4
; CHECK-NOT:   mul i32 [[laneId]], 16
;
;; The i32 field is written through an i8 GEP at constant byte offset 8. SoA
;; lowering folds that offset into the address math (add ..., 8) then divides
;; by SOAPartitionBytes (lshr 2) to land on chunk 2 (8/4=2).
;;
; CHECK:       add i32 8, %{{.*}}
; CHECK-NEXT:  lshr i32 %{{.*}}, 2
; CHECK:       store i32 42
;
; CHECK:       ret void

define spir_kernel void @test(i32 addrspace(1)* nocapture %d, <8 x i32> %r0, <8 x i32> %payloadHeader, <3 x i32> %enqueuedLocalSize, i16 %localIdX, i16 %localIdY, i16 %localIdZ, i8* nocapture readnone %privateBase) {
entry:
  %phsc = extractelement <8 x i32> %payloadHeader, i64 0
  %elsc = extractelement <3 x i32> %enqueuedLocalSize, i64 0
  %r0s18 = extractelement <8 x i32> %r0, i64 1
  %tmp0 = mul i32 %elsc, %r0s18
  %lx = zext i16 %localIdX to i32
  %tmp1 = add i32 %tmp0, %lx
  %ix = add i32 %tmp1, %phsc
  %idx = zext i32 %ix to i64
  %arr = alloca [64 x %S], align 4
  %arr8 = bitcast [64 x %S]* %arr to i8*
  call void @llvm.lifetime.start.p0i8(i64 1024, i8* nonnull %arr8)

  ; Regular field-0 GEP: float at byte offset 0 (chunk 0)
  %fp0 = getelementptr inbounds [64 x %S], [64 x %S]* %arr, i64 0, i64 %idx, i32 0
  store float 1.0, float* %fp0, align 4

  ; i8 GEP at constant byte offset 8 to access the i32 field (chunk 2).
  ; This is the pattern that MismatchDetected previously rejected for struct
  ; base types.
  %ep  = getelementptr inbounds [64 x %S], [64 x %S]* %arr, i64 0, i64 %idx
  %ep8 = bitcast %S* %ep to i8*
  %fp8 = getelementptr inbounds i8, i8* %ep8, i64 8
  %ip  = bitcast i8* %fp8 to i32*
  store i32 42, i32* %ip, align 4

  ; Regular field-1 GEP: float at byte offset 4 (chunk 1) — read back
  %fp1 = getelementptr inbounds [64 x %S], [64 x %S]* %arr, i64 0, i64 %idx, i32 1
  %fval = load float, float* %fp1, align 4

  call void @llvm.lifetime.end.p0i8(i64 1024, i8* nonnull %arr8)
  %fval_bits = bitcast float %fval to i32
  %out = getelementptr inbounds i32, i32 addrspace(1)* %d, i64 %idx
  store i32 %fval_bits, i32 addrspace(1)* %out, align 4
  ret void
}

declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture)
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture)

!IGCMetadata = !{!0}
!igc.functions = !{!6}

!0 = !{!"ModuleMD", !1, !3}
!1 = !{!"compOpt", !2}
!2 = !{!"UseScratchSpacePrivateMemory", i1 true}
!3 = !{!"FuncMD", !4, !5}
!4 = !{!"FuncMDMap[1]", void (i32 addrspace(1)*, <8 x i32>, <8 x i32>, <3 x i32>, i16, i16, i16, i8*)* @test}
!5 = !{!"FuncMDValue[1]", !2}
!6 = !{void (i32 addrspace(1)*, <8 x i32>, <8 x i32>, <3 x i32>, i16, i16, i16, i8*)* @test, !408}
!408 = !{!409, !410}
!409 = !{!"function_type", i32 0}
!410 = !{!"implicit_arg_desc", !411, !412, !413, !414, !415, !416, !417}
!411 = !{i32 0}
!412 = !{i32 1}
!413 = !{i32 7}
!414 = !{i32 8}
!415 = !{i32 9}
!416 = !{i32 10}
!417 = !{i32 13}
